<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="bondecommande.css">
    <title>Document</title>
</head>
<body>


<div class="container">

    <?php foreach ($prod as $prods): ?>

    <h2><?= $prods['productName'] ?></h2>

    <p><?= $prods['productDescription']?></p>

    <?php endforeach ?>

</div>




    
</body>
</html>