<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="bondecommande.css">
    <title>Bon de commande</title>
</head>
<body>
    


<div class="container">
<form method="GET" action="recherche.php">
        <p>
            
            <input type="text" name="search" id="search" placeholder="Tapez votre recherche"  />
            <input type="submit" value="Rechercher" />
        </p>
    </form>

    <h2>Bon de commande</h2>

    <a class="accueil" href="bondecommande.php">Retourner à l'accueil</a>

    <div class="client">

        <?php foreach ($client as $clients): ?> 
        <h3><?= $clients['customerName']?></h3>
        <h3><?= $clients['contactLastName']?> <?= $clients['contactFirstName']?></h3>
        <p><?= $clients['addressLine1'] ?> </p>
        <p><?= $clients['city']?> </p>

        <?php endforeach ?>

    </div> 
    
    <hr>

    <div class="affiche">

        <h2>Bon de commande n°<?= $_GET['orderNumber']?></h2>

        <table>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix Unitaire</th>
                    <th>Quantité</th>
                    <th>Prix Total</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ( $commande as $commandes ): ?>

                <tr>

                    <td>
                       <?= $commandes['productName'] ?></a>
                    </td>

                    <td>
                        <?= $commandes['priceEach'] ?>
                    </td>

                    <td>
                        <?= $commandes['quantityOrdered'] ?>
                    </td>

                    <td>
                        <?= number_format($commandes['prixTotal'],2) ?>
                    </td>

                </tr>

                <?php endforeach ?>

            </tbody>

                <tfoot>

                    <tr> 
                        <td colspan="3">Montant Total HT</td>
                        <td colspan='4'> <?= number_format($total['prixHT'],2) ?> </td>
                    </tr>

                    <tr> 
                        <td colspan="3">TVA(20%)</td>
                        <td colspan="4"><?= number_format($total['prixHT']*0.2,2) ?> </td>
                    </tr>

                    <tr>
                        <td colspan="3">Montant Total TTC</td>
                        <td colspan="4"><?= number_format($total['prixHT']*1.2,2) ?> </td>
                         
                    </tr>

                </tfoot>

            </table>


    </div>








</div>







</body>
</html>