<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="bondecommande.css">
    <title>Recherche</title>
</head>
<body>





<div class="container">

    <h2>Resultat de votre recherche :</h2>



    <ul>
        <?php foreach ( $cherche as $cherches ): ?>

        <li>
           <a href="detail.php?productName=<?= $cherches['productName'] ?>" ><?= $cherches['productName'] ?> </a>
        </li>
        <?php endforeach ?>
    </ul>







</div>













    
</body>
</html>