<section class="entreprise" id="home">

    <div class="container">

        <div class="logo">

            <img src="<?= $wwwUrl ?>/images/logo.png" alt="">

        </div>

    </div>

</section>


<section class="bg-light" id="prestation">

    <div class="container">

        <div class="row">

            <div class="col-lg-12 text-center">

            <h2 class="section-heading text-uppercase">Nos prestations</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>

            </div>

        </div>

        <div class="row">

            <div class="col-md-4 col-sm-6 portfolio-item">

                <img class="img-fluid" src="<?= $wwwUrl ?>/images/prestation.jpg" alt="">
            
                <div class="portfolio-caption">

                    <h4>Prestation 1</h4>
                    <p class="text-muted">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa natus quaerat nesciunt, dolor ab eum facere, consequuntur eveniet ducimus accusamus distinctio doloremque, sequi ratione sint repellendus in blanditiis at. Porro!</p>

                </div>

            </div>

            <div class="col-md-4 col-sm-6 portfolio-item">

                <img class="img-fluid" src="<?= $wwwUrl ?>/images/prestation.jpg" alt="">
            

                <div class="portfolio-caption">

                    <h4>Prestation 2</h4>
                    <p class="text-muted">Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus obcaecati, minima praesentium a nulla inventore molestiae, enim officia itaque exercitationem deleniti eum nobis illo corrupti aspernatur quod numquam adipisci assumenda!</p>

                </div>

            </div>
            
            <div class="col-md-4 col-sm-6 portfolio-item">

                <img class="img-fluid" src="<?= $wwwUrl ?>/images/prestation.jpg" alt="">
        

            <div class="portfolio-caption">

                <h4>Prestation 3</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia neque rerum eum! Veritatis dolor quia, iure rem laudantium autem, inventore libero maiores accusamus eum vitae ea, quo modi totam eligendi.</p>

            </div>

        </div>

    </div>

</section>


<section class="exemple" id="achievements">

    <div class="container">

        <div class="row">

            <div class="col-lg-12 text-center">

                <h2 class="section-heading text-uppercase">Quelques exemple de réalisation</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>

            </div>

        </div>

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

            <ol class="carousel-indicators">

                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>

            </ol>

            <div class="carousel-inner">

                <div class="carousel-item active">
                    <img class="d-block w-100" src="<?= $wwwUrl ?>/images/travaux4.jpeg" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Image 1</h5>
                        <p>lorem ipsum </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="<?= $wwwUrl ?>/images/travaux5.jpeg" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Image 1</h5>
                        <p>lorem ipsum </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="<?= $wwwUrl ?>/images/travaux6.jpeg" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Image 1</h5>
                        <p>lorem ipsum </p>
                    </div>
                </div>

            </div>

            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Préccedent</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div>

    </div>

</section>

<section class="propos" id="about">

    <div class="container">

        <div class="row">

            <div class="col-lg-12 text-center">

                <h2 class="section-heading text-uppercase">A propos de nous</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolores nostrum dignissimos voluptatibus nulla quisquam inventore modi ab dolorem exercitationem? Veniam eos praesentium, facere ipsa vel molestiae quas itaque quod fugit reprehenderit dolorum illum harum distinctio officia aliquid laudantium porro voluptatem modi placeat quidem veritatis consequatur? Modi est suscipit incidunt accusamus! Lorem ipsum dolor sit amet consectetur.</h3>

            </div>

        </div>

        <div class="row">

        <div class="col-md-4 col-sm-6 portfolio-item">

            <img class="img-fluid" src="<?= $wwwUrl ?>/images/dt.jpg" alt="">


        </div>

        <div class="col-md-4 col-sm-6 portfolio-item">

            <img class="img-fluid" src="<?= $wwwUrl ?>/images/dt.jpg" alt="">


        </div>

        <div class="col-md-4 col-sm-6 portfolio-item">

            <img class="img-fluid" src="<?= $wwwUrl ?>/images/dt.jpg" alt="">

        </div>

    </div>


    <div class="button">
        <button class="btn btnD1"><a href="<?= $requestUrl ?>/contact">Nous contacter</a></button>
    </div>

</section>
