<main>
        <!-- Affichage du template lié à la vue -->
        <h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="<?= $requestUrl ?>/user/login" method="POST">

	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
		<p></p>
	</aside>

	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="Email">E-mail :</label>
				<input id="Email" type="text" name="Email" data-required="" data-name="E-mail" value="">
			</li>
			<li>
				<label for="Password">Mot de passe :</label>
				<input id="Password" type="Password" name="Password" data-required="" data-name="Mot de passe">
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Connexion">

			<a class="button button-cancel small" href="">Annuler</a>
		</li>
	</ul>
</form>    </main>