<main>
        
<h2>Nouveau mot de passe</h2>

<form action="changePassword.php?id=<?=$_GET['id']?>" method="post">
    <fieldset>
        <legend>Tapez votre nouveau mot de passe</legend>
        <ul>
            
            <li>
            <input type="text" placeholder="password" name="psw1"/>
            </li>
            <li>
	        <input type="text" placeholder="encore password" name="psw2"/>  
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>

        <small><a href="forgot.php">Mot de passe oublié ?</a></small>
    </fieldset>
</form>    
</main>