<main>
        
<h2><i class="fa fa-pencil"></i> Login</h2>

<form class="generic-form" action="login.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Identifiez-vous</legend>
        <ul>
            
            <li>
                <label for="email">adresse mail :</label>
                <input type="email" id="email" name="email">
            </li>
            <li>
                <label for="psw">Mot de passe :</label>
                <input type="psw" id="psw" name="psw">
            </li>
                                 
        
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>

        <small><a href="forgot.php">Mot de passe oublié ?</a></small>
    </fieldset>
</form>    
</main>