







<div class="login">
    <div class="container"> 
        <h1>Login</h1>
        <form action="<?= $requestUrl ?>/login" method="POST">
            <input type="text" name="email" placeholder="Email" required="required">
            <input type="password" name="password" placeholder="Mot de passe" required="required">
            <button type="submit" class="btn btn-primary btn-block btn-large">Connexion</button>
        </form>
    </div>
</div>