<div class="haut">

    <div class="container">

        <div class="photo">

            <img src="images/portrait1.jpg" alt="">

        </div>
        
        <div class="presentation">

            <p class="moi">Nasir Tran</p>
            <p>< Développeur Web Full Stack /></p>


        </div>

    </div>

</div>

<article id="skills">

    <div class="container">

        <h2>Mes compétences</h2>

        <div class="techno">

            <h3 id="tech"> <i class="fas fa-code"></i>Technologie</h3>

                <div class="hide logo">

                    <div class="logo1">
                        <img src="logo/html.png" alt="">
                    </div>

                    <div class="logo1">
                        <img src="logo/js.png" alt="">
                    </div>

                    <div class="logo1">
                        <img src="logo/css.png" alt="">
                    </div>
                    
                    <div class="logo1">
                        <img src="logo/php.png" alt="">
                    </div>
                    
                    <div class="logo1">
                        <img src="logo/wordpress1.png" alt="">
                    </div>

                    <div class="logo1">
                        <img src="logo/git.png" alt="">
                    </div>

                    <div class="logo1">
                        <img src="logo/sql.png" alt="">
                    </div>
                    
                    <div class="logo1">
                        <img src="logo/bootstrap.png" alt="">
                    </div>

                    <div class="logo1">
                        <img src="logo/jquery.png" alt="">
                    </div>

                </div>

        </div>

        <div class="responsive">
            
            <h3><i class="fas fa-mobile-alt"></i> Responsive</h3>
            <p></p>
            
        <div>

    </div>

</article>