<!DOCTYPE html>
<html lang="fr">
<head>


     <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    
     
    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/index.css">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nasir TRAN - Développeur & Intégrateur Web</title>
</head>
<body>



    <!-- Header contenant la nav -->
    <header>
    
        <div class="container">
            <nav>
                
                <a href="#">Accueil</a>
                <a href="#skills">Compétences</a>
                <a href="#">Réalisations</a>
                <a href="#">À propos</a>
                <a href="#">Contact</a>
                
                
            </nav>
        </div>
    </header>

    <!--Fin du header -->





    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    




    <!-- Footer -->
    <footer>
        <div class="container">
        
        <p>Copyright © Nasir Tran - Portfolio 2019</p>

            
        </div>
    </footer>





<script type="text/javascript" src="main.js"></script>
</body>
</html>