<main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Ajouter un auteur</h2>

<!-- Formulaire de mise à jour d'un article -->
<form class="generic-form" action="add_author.php" method="post">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="">

    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Auteur</legend>
        <ul>
            
            <li>
            
                <label for="lastName">Nom :</label>
                <input type="text" id="lastName" name="lastName">
            </li>
            <li>
            
                <label for="firstName">Prénom :</label>
                <input type="text" id="firstName" name="firstName" >
            </li>
            
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        
        </ul>
    </fieldset>
</form>    

</main>