<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    

<main>
        
        <!-- Chargement du template PHTML spécifié par le programme PHP --><h2><i class="fa fa-cogs"></i> Panneau d'administration</h2>

<nav>
    <a href="add_Post.php">Rédiger un nouvel article</a>
</nav>


<div class="tableau" >
<table>
    <caption>Liste des articles</caption>
    <thead>
        <tr>
            <th> Titre </th>
            <th> Article </th>
            <th> Auteur </th>
            <th> Catégorie </th>
        </tr>

    </thead>
    <tbody>
    <?php foreach ($articleInfo as $articleInfos): ?>
    <tr>
        
        <td><strong> <a href="show_post.php?id=<?= $articleInfos['Id'] ?>"><?= $articleInfos['Title'] ?></a></strong> </td>
        <td><?= htmlspecialchars($articleInfos['Contents']) ?> </td>
        <td><?= htmlspecialchars($articleInfos['FirstName']), htmlspecialchars($articleInfos['LastName']) ?> </td>
        <td><?= htmlspecialchars($articleInfos['Name']) ?> </td>
        <td><a href="change_content.php?id=<?= htmlspecialchars($articleInfos['Id']) ?> "><i class="fas fa-pen"></i></a></td>
        <td><a href="remove.php?id=<?= htmlspecialchars($articleInfos['Id']) ?>"><i class="fa fa-remove"></i></a></td>
        
    </tr>
    <?php endforeach ?>

    </tbody>
</table> 
</div>

<hr>

<div class= tableau >

<table>
    <caption>Liste des utilisateurs</caption>
        <thead>
            <tr>
                <th> id </th>
                <th> Email </th>
                <th> Nom </th>
                <th> Prenom </th>
                <th> Pseudo </th>
                <th> Role </th>
            </tr>

        </thead>
        <tbody>
        <?php foreach ($userInfo as $userInfos): ?>
        <tr>
            
            <td><?= ($userInfos['id']) ?></td>
            <td><?= ($userInfos['email']) ?> </td>
            <td><?= ($userInfos['lastName'])?> </td>
            <td><?= ($userInfos['firstName']) ?></td>
            <td><?= ($userInfos['pseudo']) ?></td>
            
                <form action="change_role.php" method="POST">
                <input type="hidden" name="newrole" value="<?= $userInfos['id'] ?>">
                <td>    <select name="role" id="role">
                    
                        <option value="<?= $userInfos['role'] ?>"><?= $userInfos['role'] ?></option>

                        <?php if ($userInfos['role'] == 'admin'):?> 
                        <option value="user">user</option> 
                        <?php endif ?>

                        <?php if ($userInfos['role'] == 'user'):?> 
                        <option value="admin">admin</option> 
                        <?php endif ?>

                    </select>
                </td>
                <td>
                    <button><a href="change_role.php"><i class="fas fa-check"></i></a></button>
                </td>
                    </form>
                    
            </td>
            
            
        </tr>
        <?php endforeach ?>

    </tbody>
</table> 
</div>

<hr>

<div class="tableau">

<table >
    <caption>Liste des auteurs</caption>
    <caption><a href="add_author.php"><i class="far fa-arrow-alt-circle-right"></i>ajouter un auteur</a></caption>

        <thead>
            <tr>
                <th> id </th>
                <th> Nom </th>
                <th> Prénom </th>
            </tr>

        </thead>
        <tbody>
        <?php foreach ($authorInfo as $authorInfos): ?>
        <tr>
            
            <td><?= htmlspecialchars($authorInfos['Id']) ?></td>
            <td><?= htmlspecialchars($authorInfos['lastName'])?> </td>
            <td><?= htmlspecialchars($authorInfos['firstName']) ?></td>
            
        <td><a href="remove_author.php?id=<?= htmlspecialchars($authorInfos['Id']) ?>"><i class="fa fa-remove"></i></a></td>
        
        </tr>
        <?php endforeach ?>
        

    </tbody>
</table> 
</div>

<hr>

<div class="tableau">

<table>
    
    <caption>Liste des catégories</caption>
    <caption><a href="add_category.php"><i class="far fa-arrow-alt-circle-right"></i>ajouter une catégorie</a></caption>
        <thead>
            <tr>
                <th> id </th>
                <th> Nom </th>
            </tr>

        </thead>
        <tbody>
        <?php foreach ($categoryInfo as $categoryInfos): ?>
        <tr>
            
            <td><?= htmlspecialchars($categoryInfos['Id']) ?></td>
            <td><?= htmlspecialchars($categoryInfos['Name'])?> </td>
            
        <td><a href="remove_category.php?id=<?= htmlspecialchars($categoryInfos['Id']) ?>"><i class="fa fa-remove"></i></a></td>
            
        </tr>
        <?php endforeach ?>

    </tbody>
</table> 
</div>

</main>






</body>
</html>