<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    

<main>
<h2><i class="fa fa-home"></i> Accueil</h2>


<ul class="post-list">
        <li class="post">
            <?php foreach ($articleInfo as $articleInfos): ?>
            <h3><i class="fa fa-hand-o-right"></i> <a href="show_post.php?id=<?= htmlspecialchars($articleInfos['Id']) ?>"><?=  htmlspecialchars($articleInfos['Title']) ?></a></h3>
            <p><?= htmlspecialchars($articleInfos['Contents'])?></p>

            <small>Rédigé par <?= htmlspecialchars($articleInfos['FirstName']).' '.htmlspecialchars($articleInfos['LastName']) ?> le <?= htmlspecialchars($articleInfos['CreationDate']) ?></small>

            <?php endforeach ?>
                    
        </li>
</ul>


</main>


</body>
</html>
