<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Another One ! #Blog</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="index.php"><i class="fa fa-microphone"></i>Another One #BLOG</a></h1>
        <nav>
            
            <?php if(array_key_exists('firstName', $_SESSION) ) : ?>
            <a href="#"><i class="far fa-user"></i> <?= $_SESSION['pseudo']?></a>
            <a href="logout.php"><i class="far fa-times-circle"></i>Deconnexion</a>

            <?php if($_SESSION['role'] == 'admin') { ?>
            <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
            <?php } ?>

            <?php else : ?>

            <a href="login.php"><i class="fas fa-sign-in-alt"></i>M'identifier</a>
            <a href="register.php"><i class="far fa-hand-peace"></i>M'enregistrer</a>

            <?php endif ?>
            
        </nav>
    </header>
    

    <main>
        
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small> And zat's waye wiyare ireeeee</small>
    </footer>
</body>
</html>
