<main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'ajout d'enregistrement d'un nouvel utilisateur -->
<h2><i class="fa fa-pencil"></i> Inscription</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="register.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Incrivez-vous</legend>
        <ul>
            <li>
                <label for="lastName">Nom :</label>
                <input type="lastName" id="lastName" name="lastName">
            </li>
            <li>
                <label for="firstName">Prénom :</label>
                <input type="firstName" id="firstName" name="firstName">
            </li>
            <li>
                <label for="email">adresse mail :</label>
                <input type="email" id="email" name="email">
            </li>
            <li>
                <label for="pseudo">Pseudo :</label>
                <input type="pseudo" id="pseudo" name="pseudo">
            </li>
            <li>
                <label for="password">Mot de passe :</label>
                <input type="password" id="password" name="password">
            </li>
                                 
        
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>    
</main>