<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'article de blog détaillé avec les commentaires -->
<h2><i class="fa fa-file-text-o"></i> Article</h2>

<!-- Article du blog -->
<section class="post">
    
    <h3><?= $articleInfo['Title']?></h3>
    <article><?= $articleInfo['Contents']?></article>
    <small>
        Rédigé par <?= $articleInfo['FirstName']?>,<?= $articleInfo['LastName'] ?>       le <?= $articleInfo['CreationDate']?>    </small>
    
</section>

<hr>

<!-- Liste des commentaires de l'article du blog -->
    <ul class="comment-list">

        <?php foreach ($com as $coms): ?>

        <li>
           <H4><i class="fa fa-comment"></i><?= $coms['Pseudo'] ?> </H4> 
           <article> <?= $coms['Contents'] ?> </article>
           <small>Rédigé le <?= $coms['CreationDate'] ?> </small>
        </li>

        <?php endforeach ?>
    

    </ul>

<hr>

<!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
<form class="generic-form" action="show_post.php?id=<?= $_GET['id']?>" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<?=$_GET['id']?>">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="nickName">Pseudo :</label>
                <input type="text" id="nickName" name="nickName">
            </li>
            <li>
                <label class="textarea" for="contents">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>    </main>
</body>
</html>